#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ $# -ge 1 ]
then
    java -cp "${SCRIPT_DIR}/target/yareakh-keyring.jar" com.yareakh.keyring.cli.CreatePassword $1 $2
fi
