CREATE TABLE ROLE (
  NAME VARCHAR(32) NOT NULL,
  DESCRIPTION VARCHAR(128),
  CONSTRAINT ROLE_PK PRIMARY KEY (NAME)
);

CREATE TABLE ROLE_TO_KEY_PAIR (
    ROLE_NAME VARCHAR(32) NOT NULL,
    KEY_PAIR_ID BIGINT NOT NULL,
    CONSTRAINT ROLE_TO_KEY_PAIR_FK1 FOREIGN KEY (ROLE_NAME) REFERENCES ROLE(NAME),
    CONSTRAINT ROLE_TO_KEY_PAIR_FK2 FOREIGN KEY (KEY_PAIR_ID) REFERENCES KEY_PAIR(ID)
);