DROP TABLE IF EXISTS ROLE_TO_KEY_PAIR;
CREATE TABLE ROLE_TO_KEY_PAIR (
      ROLE_NAME VARCHAR(32) NOT NULL,
      KEY_PAIR_NAME VARCHAR(64) NOT NULL,
      CONSTRAINT ROLE_TO_KEY_PAIR_FK1 FOREIGN KEY (ROLE_NAME) REFERENCES ROLE(NAME),
      CONSTRAINT ROLE_TO_KEY_PAIR_FK2 FOREIGN KEY (KEY_PAIR_NAME) REFERENCES KEY_PAIR(NAME)
);

INSERT INTO ROLE (NAME, DESCRIPTION) values ('admin', 'System Administrator');

INSERT INTO KEY_PAIR (
    PUBLIC_KEY,
    PRIVATE_KEY,
    PASSWORD,
    NAME
) VALUES (
    E'\x7f\x7f',
    E'\x7f\x7f',
    'b2ffa5cefaddb42d75f4a43535faad6b1df7a7954afbf8ed5096eff7d5e63110',
    'System Administrator'
);

INSERT INTO ROLE_TO_KEY_PAIR (ROLE_NAME, KEY_PAIR_NAME) VALUES ('admin', 'System Administrator');